Add usage example to APIDoc and updated README
IBM-Swift/Kitura-Session pull request #51
Opened 2018-07-11 13:33 UTC by helenmasters

* Added usage example to APIDoc for Session and CookieParameters
 * Added further descriptions to parameters in APIDoc
 * Fixed typos in APIDoc
 * Added APIDoc link to the README header
 * Added missing standard sections to README
 * Reworded parts of the README

2018-07-16 12:52 UTC, djones6 requested changes
Good fixes, I feel I'm nitpicking here but some wording suggestions.

2018-07-16 12:52 UTC, djones6 commented on README.md
> +First an instance of `RedisStore` is created (see [`KituraSessionRedis`](https://github.com/IBM-Swift/Kitura-Session-Redis) for more information), then an instance of `Session` with the store as a pa
I'd prefer
> An instance of `RedisStore` is created that will be used to persist session data (see [`KituraSessionRedis`](https://github.com/IBM-Swift/Kitura-Session-Redis) for more information).  An instance of `Session` is then created, specifying *redisStore* as the session store.  Finally, the *session* instance is registered as a middleware on the desired path.

2018-07-16 12:52 UTC, djones6 commented on Sources/KituraSession/CookieParameter.swift
> +    /// The cookie's path attribute, this defines the path for which this cookie should be supplied.
> The cookie's path attribute. This specifies the path for which the cookie is valid. The client should only provide this cookie for requests on this path.

2018-07-16 12:52 UTC, djones6 commented on Sources/KituraSession/CookieParameter.swift
> +    /// The cookie's name, defaults to "kitura-session-id".
name, defaults to  ->  name. Defaults to

2018-07-16 12:52 UTC, djones6 commented on Sources/KituraSession/CookieParameter.swift
> +    /// The cookie's secure attribute, this indicates whether the cookie should be provided only
attribute, this indicates whether  ->  attribute, indicating whether

2018-10-09 09:32 UTC, Andrew-Lees11 commented on Sources/KituraSession/Session.swift
> +/// ```
Can we add an example of using the session within a route? E.g.
```
router.post("/session") {request, response, next in
            request.session?["key"] = "value"
            next()
        }
router.get("/session") {request, response, next in
            let value = request.session?["key"] as? String
            next()
        }
```

2018-10-09 09:33 UTC, Andrew-Lees11 commented on README.md
>  ```
Could we add using the session within a route to this example. E.g:
 router.post("/session") {request, response, next in
            request.session?["key"] = "value"
            next()
        }
router.get("/session") {request, response, next in
            let value = request.session?["key"] as? String
            next()
        }

2019-01-30 15:38 UTC, Andrew-Lees11 commented
I have addressed mine and @djones6 review comments and rebased this PR on top of the current master. 
I also added readme examples for Codable and TypeSafeSession to the README.

2019-01-30 15:41 UTC, Andrew-Lees11 approved these changes

2019-02-13 11:35 UTC, djones6 approved these changes

2019-02-13 11:37 UTC, merged